namespace Un4seen.Bass
{
	public enum BASSStreamFilePosition
	{
		BASS_FILEPOS_CURRENT = 0,
		BASS_FILEPOS_DOWNLOAD = 1,
		BASS_FILEPOS_END = 2,
		BASS_FILEPOS_START = 3,
		BASS_FILEPOS_CONNECTED = 4,
		BASS_FILEPOS_BUFFER = 5,
		BASS_FILEPOS_SOCKET = 6,
		BASS_FILEPOS_ASYNCBUF = 7,
		BASS_FILEPOS_SIZE = 8,
		BASS_FILEPOS_BUFFERING = 9,
		BASS_FILEPOS_WMA_BUFFER = 1000,
		BASS_FILEPOS_HLS_SEGMENT = 0x10000
	}
}
